In [1]:
import numpy as np

# The Numpy Array

In [2]:
# Single Dimensional
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
# Multi Dimensional
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print(a) 

[[1 2 3]
 [4 5 6]]


## Can Index and slice (just like a Python List)!

In [17]:
a = np.array(range(10))

print("Entire array:")
print(a)
print()
print("Individual index 3:")
print(a[3])
print()
print("Index slice from 1 to 5:")
print(a[1:5])

Entire array:
[0 1 2 3 4 5 6 7 8 9]

Individual index 3:
3

Index slice from 1 to 5:
[1 2 3 4]


# When and why use them over Lists?

## Less Memory

In [12]:
import sys 

S= range(1000) 

# list of 1000 elements  
L = list(S)
print("Size of the python list in bytes:", sys.getsizeof(L)*len(L)) 
  
# Numpy array of 1000 elements  
D= np.array(S) 
print("Size of the numpy array in bytes:", D.size*D.itemsize) 


Size of the python list in bytes: 8056000
Size of the numpy array in bytes: 4000


## Convenient Array Creation Methods

In [5]:
#create array with all zeros
zero_arr = np.zeros(10)
print("An array with all zeros:")
print(zero_arr)
print()

#create an n-dimensional identity matrix
id_matrix = np.eye(3)
print("An Identity Matrix:")
print(id_matrix)
print()

# A range with a specified number of elements between them
ls = np.linspace(0,100,1001)
print("NP array with 1001 values evenly spaced between 1 through 100")
print(ls)
print()

# Array with random integers
rand = np.random.random_integers(1,6,10)
print("NP array with random integers")
print(rand)
print()

An array with all zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

NP array with 1001 values evenly spaced between 1 through 100
[  0.    0.1   0.2 ...  99.8  99.9 100. ]

NP array with random integers
[1 4 2 5 6 3 6 4 4 2]



## More Convenient Math Operations

In [14]:
#Multiply each np array element by 2
a = np.random.random_integers(1,6,10)

b = np.random.random_integers(1,6,10)

print("Array a:")
print(a)
print("Array b:")
print(b)
print()
print("Elements in array a doubled:")
print(a*2)
print()
print("Sum of array a and b:")
print(a + b)

Array a:
[2 1 1 2 3 3 4 2 3 1]
Array b:
[6 5 4 6 3 2 6 4 3 4]

Elements in array a doubled:
[4 2 2 4 6 6 8 4 6 2]

Sum of array a and b:
[ 8  6  5  8  6  5 10  6  6  5]


In [7]:
print("Standard Deviation of elements:")
print(a.std())

print()

print("Cumulative Sum:")
print(a.cumsum())

Standard Deviation of elements:
1.7578395831246945

Cumulative Sum:
[ 5 11 16 20 22 26 32 34 40 41]
