In [1]:
import numpy as np

# The Numpy Array

In [2]:
# Single Dimensional
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# Multi Dimensional
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print(a) 

# When and why use them over Lists?

## Less Memory

In [4]:
# importing system module 
import sys 
  
# declaring a list of 1000 elements  
S= range(1000) 
  
# printing size of each element of the list 
print("Size of each element of list in bytes: ",sys.getsizeof(S)) 
  
# printing size of the whole list 
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S)) 
  
# declaring a Numpy array of 1000 elements  
D= np.array(S) 
  
# printing size of each element of the Numpy array 
print("Size of each element of the Numpy array in bytes: ",D.itemsize) 
  
# printing size of the whole Numpy array 
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize) 


Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


## Convenient Array Creation Methods

In [16]:
zero_arr = np.zeros(10)

id_matrix = np.eye(3)

ls = np.linspace(0,100,1001)

rand = np.random.random_integers(1,6,10)

gauss_rand = np.random.normal(100,15,10)

range_arr = np.arange(1,50,2)

In [17]:
id_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## More Convenient Math Operations

In [18]:
#Multiply each np array element by 2
a = np.random.random_integers(1,6,10)

print(a)

print(a*2)

[6 4 1 6 4 2 2 6 5 6]
[12  8  2 12  8  4  4 12 10 12]


In [19]:
a.std()

1.8330302779823362

In [20]:
a.cumprod()

array([     6,     24,     24,    144,    576,   1152,   2304,  13824,
        69120, 414720], dtype=int32)