In [2]:
import numpy as np

# The Numpy Array

In [3]:
# Single Dimensional
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
# Multi Dimensional
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print(a) 

[[1 2 3]
 [4 5 6]]


# When and why use them over Lists?

## Less Memory

In [5]:
import sys 
  
# list of 1000 elements  
S= range(1000) 
print("Size of the python list in bytes:",sys.getsizeof(S)*len(S)) 
  
# Numpy array of 1000 elements  
D= np.array(S) 
print("Size of the numpy array in bytes:",D.size*D.itemsize) 


Size of the python list in bytes: 48000
Size of the numpy array in bytes: 4000


## Convenient Array Creation Methods

In [7]:
#create array with all zeros
zero_arr = np.zeros(10)
print("An array with all zeros:")
print(zero_arr)
print()

#create an n-dimensional identity matrix
id_matrix = np.eye(3)
print("An Identity Matrix:")
print(id_matrix)
print()

# A range with a specified number of elements between them
ls = np.linspace(0,100,1001)
print("NP array with 1001 values evenly spaced between 1 through 100")
print(ls)
print()

# Array with random integers
rand = np.random.random_integers(1,6,10)
print("NP array with random integers")
print(rand)
print()

An array with all zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

NP array with 1001 values evenly spaced between 1 through 100
[  0.    0.1   0.2 ...  99.8  99.9 100. ]

NP array with random integers
[4 5 2 1 2 6 5 3 4 5]



## More Convenient Math Operations

In [10]:
#Multiply each np array element by 2
a = np.random.random_integers(1,6,10)

print("Array as is:")
print(a)
print()
print("Elements doubled:")
print(a*2)

Array as is:
[5 4 2 2 5 6 3 2 3 3]

Elements doubled:
[10  8  4  4 10 12  6  4  6  6]


In [13]:
print("Standard Deviation of elements:")
print(a.std())

print()

print("Cumulative Sum:")
print(a.cumsum())

Standard Deviation of elements:
1.3601470508735443

Cumulative Sum:
[ 5  9 11 13 18 24 27 29 32 35]
